#!/bin/bash
export scaffold_dir="/usr/local/PatchDock/scaffolds"
mv pdbs pdbs_old
mkdir pdbs
#mkdir patchdock_out
cd patchdock_out
ls *.out > outlist

for f  in $(sed -n '=' outlist)
do
score1=0
score2=0
score3=0
outfile=$(head -$f outlist| tail -1) 
score1=`grep "   1 |" ${outfile} | awk '{printf ($3)}'`
score2=`grep "   2 |" ${outfile} | awk '{printf ($3)}'`
score3=`grep "   3 |" ${outfile} | awk '{printf ($3)}'`
number=`echo ${outfile} | sed 's/.out//g'`

   if [ ${score3} -gt 12000 ]; then
	   echo $score2 > log
	   echo $score3 >> log
	   transOutput.pl ${outfile} 1 3
	   mv ${outfile}.1.pdb ../pdbs/${score1}_${number}.pdb
	   mv ${outfile}.2.pdb ../pdbs/${score2}_${number}.pdb
	   mv ${outfile}.3.pdb ../pdbs/${score3}_${number}.pdb
   elif [ ${score2} -gt 12000 ]; then
	   echo $score2 >> log
	   transOutput.pl ${outfile} 1 2
	   mv ${outfile}.1.pdb ../pdbs/${score1}_${number}.pdb
	   mv ${outfile}.2.pdb ../pdbs/${score2}_${number}.pdb
   else
	   transOutput.pl ${outfile} 1 1
	   mv ${outfile}.1.pdb ../pdbs/${score1}_${number}.pdb

   fi

done

rm outlist
cd ..

