#!/bin/bash
#SBATCH -p gpu
#SBATCH --mem=32g
#SBATCH --gres=gpu:rtx2080:1
#SBATCH -c 3
#SBATCH --output=example_3.out

if [ ${#} -eq 0 ]; then
        echo "Usage: proteinmpnn_sym [folder with target pdb] [target chain (optional, default is X Z)]"
        exit 1
elif [ ${#} -gt 2 ]; then
	echo "Invalid argument number"
	exit 1
fi

target_dir=$1

if [ ${#} -eq 1 ]; then
        echo "target chain is X Z(default)"
	target_chain="X Z"
elif [ ${#} -eq 2 ]; then
	echo "target chain is $2"
	target_chain=$2
fi

if [ ! -d ${target_dir} ]; then
        echo "no protein pdb dir "
        exit 1
fi

source /home/hnc/miniconda3/bin/activate /home/hnc/miniconda3/envs/mlfold
folder_with_pdbs="${target_dir}/"
output_dir="output"
proteinmpnn=/usr/local/ProteinMPNN
if [ ! -d $output_dir ]
then
	    mkdir -p $output_dir
fi

chains_to_design="${target_chain}"

path_for_parsed_chains="$output_dir/parsed_pdbs.jsonl"
path_for_assigned_chains="$output_dir/assigned_pdbs.jsonl"
path_for_tied_positions="$output_dir/tied_pdbs.jsonl"
path_for_designed_sequences="$output_dir/temp_0.2"
#tied_positions="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56, 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56" 

python3 $proteinmpnn/helper_scripts/parse_multiple_chains.py --input_path=$folder_with_pdbs --output_path=$path_for_parsed_chains 

python $proteinmpnn/helper_scripts/assign_fixed_chains.py --input_path=$path_for_parsed_chains --output_path=$path_for_assigned_chains --chain_list "$chains_to_design" 


python $proteinmpnn/helper_scripts/make_tied_positions_dict.py --input_path=$path_for_parsed_chains --output_path=$path_for_tied_positions --chain_list "$chains_to_design" 


#python $proteinmpnn/helper_scripts/make_tied_positions_dict.py --input_path=$path_for_parsed_chains --output_path=$path_for_tied_positions --chain_list "$chains_to_design" --homooligomer 1 


python3 $proteinmpnn/protein_mpnn_run.py \
        --jsonl_path $path_for_parsed_chains \
        --chain_id_jsonl $path_for_assigned_chains \
        --tied_positions_jsonl $path_for_tied_positions \
        --out_folder $output_dir \
        --num_seq_per_target 2 \
        --sampling_temp "0.2" \
        --seed 37 \
        --batch_size 1

echo "Done, output directory is seqs"
