#!/bin/bash

if [ ${#} -eq 0 ]; then
        echo "afp [.fasta file]"
        exit 1
fi

if [[ $1 != *.fasta ]]; then
	echo "Please input .fasta file"
	exit 1
fi

if [ ! -e $1 ]; then
        echo "no fasta file in this directory"
        exit 1
fi

inputfastaname=`basename $1 .fasta`

export DOWNLOAD_DIR="/ssddata/alphafold_DB"
export output_dir=$PWD
export PATH="/home/hnc/miniconda3/bin:$PATH"
source activate af
python3 /home/hnc/alphafold/docker/run_docker.py \
  --fasta_paths=$1 \
  --max_template_date=2023-05-14 \
  --model_preset=monomer \
  --db_preset=reduced_dbs \
  --output_dir=$output_dir \
  --num_multimer_predictions_per_model=1 \
  --data_dir=$DOWNLOAD_DIR

cd $inputfastaname
source activate alphapickle
python3 /home/hnc/alphapickle/run_AlphaPickle.py -od ./
echo "Done, output directory is $inputfastaname"

