#!/bin/bash
#echo "ef_run seqs"
#echo "run this script on the directory containing seqs"

if [ ${#} -eq 0 ] ; then
        echo "Please type input directory(ex.seqs) after command."
        echo "af_run [input dir]"
        exit 1
elif [ ${#} -gt 1 ] ; then
	echo "Invalid file format"
	exit 1
else 	input_dir=$1
fi

if [ ! -d ${input_dir} ]; then
        echo "no input pdb folder in this directory"
        exit 1
fi

find ${input_dir}/*fa > falist
linenumber=`wc -l falist | awk '{printf ($1)}'`

if [ ! -d ef ]; then
	mkdir ef
else
	mv -f ef ef_old
	mkdir ef
fi

if [ -f "ef/ef.fasta" ]; then
rm ef/ef.fasta
fi

for f in $(seq 1 $linenumber)
do
        filename=`head -$f falist| tail -1`
	fa_name=`basename $filename .fa`
	for g in $(seq 1 5)
	do
	printf ">" >> ef/ef.fasta
	echo ${fa_name}_ef${g}>> ef/ef.fasta
        grep -r -A 1 -h "sample=$g" $filename > ttt
	head -2 ttt | tail -1 >> ef/ef.fasta
	rm ttt
        done

done
cd ef

efold ef.fasta | tee ../ef.log
cd ..



echo "Esmfold is running in background"


