#!/bin/bash
export scaffold_dir="/usr/local/PatchDock/scaffolds"
#mkdir pdbs
#mkdir patchdock_out
for f  in $(seq $3 $2 22900)
do
score1=0
score2=0
score3=0
ligandpdb=$(head -$f $scaffold_dir/recommended_scaffolds.list| tail -1) 
echo "$ligandpdb"
buildParams_modi.pl $1 "/usr/local/PatchDock/scaffolds/$ligandpdb" 4 Default ${f}_params.txt
patch_dock.Linux ${f}_params.txt $f.out >patch_dock_${f}.log
score1=`grep "   1 |" $f.out| awk '{printf ("%05.0f",$3)}'`
score2=`grep "   2 |" $f.out| awk '{printf ("%05.0f",$3)}'`
score3=`grep "   3 |" $f.out| awk '{printf ("$05.0f",$3)}'`
#echo "$score"

   if [ ${score3} -gt 12000 ]; then
          transOutput.pl $f.out 1 3
          mv $f.out.1.pdb pdbs/${score1}_${f}.pdb
          mv $f.out.2.pdb pdbs/${score2}_${f}.pdb
          mv $f.out.3.pdb pdbs/${score3}_${f}.pdb
   elif [ ${score2} -gt 12000 ]; then
          transOutput.pl $f.out 1 2
          mv $f.out.1.pdb pdbs/${score1}_${f}.pdb
          mv $f.out.2.pdb pdbs/${score2}_${f}.pdb
   else
	  transOutput.pl $f.out 1 1
	  mv $f.out.1.pdb pdbs/${score1}_${f}.pdb
   fi


mv $f.out patchdock_out
rm -f  ${f}_params.txt
rm -f  patch_dock_${f}.log
done
