#!/bin/bash
#######################

echo " !!!!!!! YOU SHOULD REMOVE CONFIG_FILE FIRST !!!!!!!"
# MPNN READY
CONFIG_FILE="$HOME/proteindesign_config/increment_value.conf"

# Check if the configuration file exists and read the increment value
if [ -f "$CONFIG_FILE" ]; then
    increment=$(<"$CONFIG_FILE")
else
    # If the file doesn't exist, create it with a default value of 100
    mkdir -p "$HOME/proteindesign_config"
    echo 20 > "$CONFIG_FILE"
    increment=20
fi
#######################


#######################
echo "calculate the original energy"
uglee_em $1 
input=$(basename $1 .pdb)
prodigy ${input}_start.pdb --selection A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,Y,Z X > "summary_original"
original_prodigy=$(grep "Predicted dissociation constant" "summary_original" | awk -F'e-' '{print $2}' | tr -d '^M')

# If the value starts with a 0, remove it
if [[ $original_prodigy == 0* ]]; then
    original_prodigy=${original_prodigy#0}
fi

echo " The original prodigy value is $original_prodigy"
rm ${input}_start.pdb
rm summary_original
echo "original energy calculated done"
#######################



#######################
echo "MPNN starts"
uglee_ligandmpnn $1 $increment 
echo "MPNN done"
#######################


#######################
# ESMFOLD
echo "ESMFOLD starts"
uglee_esmfold  ${input}_outputs
echo "ESMFOLD done"
#######################








#######################
echo "align starts"
mkdir patchdock_dir
cp ${input}.pdb patchdock_dir
rm ef.log falist ttt
uglee_align patchdock_dir ef 
echo "align done"
#######################


#######################
echo "Chainge complex pdb into EM complex pdb"
find ./ -maxdepth 1 -name '*ef*.pdb' > align_list
while read -r filename; do
    filename2=$(basename "$filename" .pdb)
    uglee_em "${filename}" 
    rm "${filename}"
    mv "${filename2}_start.pdb" "${filename}"
done <align_list
echo "Chainge complex pdb into EM complex pdb done"
#######################

#######################
# esmfold cutoff
echo "ESMFOLD cutoff starts"
find ./ -maxdepth 1 -name '*ef*.pdb' > Emfold_cutoff_list
while read -r filename; do
    prodigy_output=$(prodigy "${filename}" --selection 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,Y,Z' X --distance-cutoff 2 2>&1)
    if echo "$prodigy_output" | grep -q "ValueError: No contacts found for selection"; then
        echo "No ESM_clash  in $filename by prodigy"
    else
        echo "ESM_Clash in $filename."
        rm "$filename"
    fi
done < Emfold_cutoff_list
rm Emfold_cutoff_list
echo "ESMFOLD cutoff done"
#######################








#######################
echo "colabdock starts"
uglee_export_chain_name ./*ef*.pdb 

mini=$(head -n 1 chain.txt)
recep=$(sed -n '2p' chain.txt)

find ./ -maxdepth 1 -name '*ef*.pdb' > Emfold_finished_list
touch colabdock_finished_list


while read -r filename; do
    filename2=$(basename "$filename" .pdb)
    uglee_colab_1vN ${filename} ${mini},${recep} >> colabdock.log
    
    cd results_${filename2}/docked
    for old in {1st,2nd,3rd,4th,5th}_best.pdb; do
        new="${filename2}_${old}"
        mv "$old" "$new"
    done
    cd ../..
    
    find ./results_${filename2}/docked -maxdepth 1 -name '*.pdb' >> colabdock_finished_list
done < Emfold_finished_list

rm LICENSE README.md chain.txt config.py extract_rest.py README.md rest requirements.txt main.py
rm -r colabdesign colabdock params protein __pycache__ 

echo " cdockrun_done"
#######################




#####################
echo "Checking for clashes using Gromax"

while read -r filename; do
    if uglee_detectclash_gmx "$filename" | grep -q "Yes"; then
        echo "Clash detected. Deleting $filename."
        rm "$filename"
    else
        echo "No clash detected in $filename." 
    fi
done < colabdock_finished_list



touch clash_gm_finished_list

while read -r filename; do
    filename2=$(basename "$filename" .pdb)
    find "./results_${filename2}/docked" -maxdepth 1 -name '*.pdb' >> clash_gm_finished_list
done < Emfold_finished_list

echo " clashed in gm pdb files are deleted"
#####################




#####################
echo "Starting Energy Minimization (EM)"

while read -r filename; do
    uglee_em "$filename" >> optimizing.log 
done < clash_gm_finished_list

echo "Energy Minimization (EM) completed"
#####################






#####################
# Create or clear the log file for recording Prodigy's output and errors
echo "clash detection by prodigy starts"
> prodigy_clash_log


while IFS= read -r filename; do
    base_filename=$(basename "$filename" .pdb)
    # Run Prodigy, redirect stderr to stdout for error detection and append stdout to log
    prodigy_output=$(prodigy "${base_filename}.pdb" --selection 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,Y,Z' X --distance-cutoff 2 )
    exit_status=$?
    echo "$prodigy_output" >> prodigy_clash_log
    if [[ $exit_status -ne 0 ]] || echo "$prodigy_output" | grep -qi 'error'; then
        echo "NNNNNOOOOOO CLASH IN $filename."
    else
        echo "Clash in $filename."
        rm "$filename"
    fi
done < clash_gm_finished_list



# Prepare a list of PDB files for further analysis based on another list
touch clash_pymol_finished_list

while IFS= read -r filename; do
    base_filename=$(basename "$filename" .pdb)
    find "./results_${base_filename}/docked" -maxdepth 1 -name '*.pdb' >> clash_pymol_finished_list
done < Emfold_finished_list

echo "Clash detection and file handling by prodigy complete."
#####################









#####################
echo "Starting PRODIGY analysis"
echo "Comparing Kd values with the original one"

while read -r filename; do
    filename4=$(basename "$filename" .pdb)
    prodigy "${filename4}_start.pdb" --selection A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,Y,Z X > "log_${filename4}.log"
    
    new_result=$(grep "Predicted dissociation constant" "log_${filename4}.log" | awk -F'e-' '{print $2}' | tr -d '\r')
    
    if [[ -z "$new_result" ]]; then
        echo "No Kd value found for $filename4. Skipping."
        continue
    fi
    
    if (( $(echo "$new_result > $original_prodigy" | bc -l) )); then
        echo "Awesome! $filename has a better Kd"
        grep "dissociation" "log_${filename4}.log" >> "summary_${filename4}"
    else
        echo "Kd value not improved. Deleting $filename."
        rm "$filename"
    fi
    
    rm "log_${filename4}.log"
done < clash_pymol_finished_list

echo "PRODIGY analysis completed"
#####################







#####################
echo "Generating summary"

find . -maxdepth 1 -name 'summary_*' ! -name 'summary_list' ! -name 'summary_all' > summary_list

touch summary_all
while read -r filename; do
    echo -n "$filename " >> summary_all
    head -n 1 "$filename" >> summary_all
done < summary_list


echo "Summary generated"
echo "OPTIMIZING DONE!"
#####################



#####################
# Check if the word "dissociation" is in summary_all
if grep -q "dissociation" summary_all; then
    echo "Better mini-protein found"
    rm $CONFIG_FILE
else
    echo "No better mini-protein found. Retrying with incremented directory name."
    
    current_dir=$(basename "$PWD")
    parent_dir=$(dirname "$PWD")
    
    if [[ $current_dir =~ ^[0-9]+_ ]]; then
        prefix=${current_dir%%_*}
        suffix=${current_dir#*_}
        new_prefix=$((prefix + 1))
        new_dir="${new_prefix}_${suffix}"
    else
        new_dir="1_${current_dir}"
        new_prefix=1
    fi
    
    # Increment the value by 100 for the next round
    new_increment=$((increment + 20))
    
    # Update the configuration file with the new increment value
    echo "$new_increment" > "$CONFIG_FILE"
    
    mkdir -p "$parent_dir/$new_dir"
    cp "$1" "$parent_dir/$new_dir"
    cd "$parent_dir/$new_dir"
    # No need to modify the script; it will read the new increment from the config file
    $0 "${1##*/}"
fi
#####################





